### ISSUE TITLE
Ability to configure the storage path

### ISSUE THREAD

**Issue by BrunoSpy** [zuinqstudio/cmis_4_redmine_2#1]
It would be nice to be able to configure the storage path on a per project basis.

This is really needed when you already have a space on your CMIS server.

Thanks.

**Comment by cforce** [comment]
+1

**Comment by BrunoSpy** [comment]
Done here https://github.com/BrunoSpy/cmis_4_redmine_2

**Comment by BrunoSpy** [comment]
See pull request https://github.com/zuinqstudio/cmis_4_redmine_2/pull/6
