### ISSUE TITLE
no such file to load -- active_cmis

### ISSUE THREAD

**Issue by bsmithi** [zuinqstudio/cmis_4_redmine_2#2]
Gem could not be loaded by rake and passenger.

OS: Ubuntu 12.04 LTS and CentOS 6.x
All info below is form Ubuntu

ruby -v
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

rake -V
rake, version 0.9.2.2

gem -v
2.0.2

*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
no such file to load -- active_cmis
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`require'
/home/vhost/redmine/plugins/redmine_cmis/init.rb:17
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`require'
/home/vhost/redmine/lib/redmine/plugin.rb:129:in `load'
/home/vhost/redmine/lib/redmine/plugin.rb:120:in`each'
/home/vhost/redmine/lib/redmine/plugin.rb:120:in `load'
/home/vhost/redmine/config/initializers/30-redmine.rb:13
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in`load'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in`load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/engine.rb:588
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/engine.rb:587:in`each'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/engine.rb:587
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/initializable.rb:30:in`run'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/initializable.rb:55:in `run_initializers'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/initializable.rb:54:in`each'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/application.rb:136:in`initialize!'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/railtie/configurable.rb:30:in `send'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/railtie/configurable.rb:30:in`method_missing'
/home/vhost/redmine/config/environment.rb:18
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/application.rb:103:in `require'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/application.rb:103:in`require_environment!'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/application.rb:292:in `initialize_tasks'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:157:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`run'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19
/usr/local/bin/ruby_noexec_wrapper:14
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by zuinqstudio** [comment]
I'm assuming you're using Redmine 2.x

Have you installed the active_cmis gem and added the reference to the Gemfile?

**Comment by bsmithi** [comment]
I forgot to tell but you are right i'm using Redmine 2.x
I've followed te following tutorials:
http://www.redmine.org/plugins/cmis_4_redmine_2
http://www.xaop.com/blog/2010/04/13/gentle-introduction-to-activecmis/
http://nokogiri.org/tutorials/installing_nokogiri.html

gem install nokogiri
gem install active_cmis

And succesfully tested with the irb command.
I've also made a little test script in ruby

#!/usr/bin/env ruby
require 'rubygems'
require 'active_cmis'

**Comment by bsmithi** [comment]
What do you mean by "and added the reference to the Gemfile?"
The redmine plugins references to this gem

**Comment by zuinqstudio** [comment]
In your redmine root folder, you may find a file named 'Gemfile'. You need to add additional dependencies at the start of the file, like

gem 'active_cmis', '0.3.2'
gem 'nokogiri'

**Comment by bsmithi** [comment]
Thanks a lot!
It works on CentOS. I need to reinstall ruby on ubuntu because I wrecked it. But it seems you solution also works on my ubuntu machine.

I saw those instructions many sites but i did'nt realize it belongs to the Gemfile in redmine.

**Comment by zuinqstudio** [comment]
Glad it worked. Enjoy!
