### ISSUE TITLE
Configuración

### ISSUE THREAD

**Issue by Takyo** [zuinqstudio/cmis_4_redmine_2#5]
Hola, me acabo de instalar la última versión para Redmine 2.3 y resulta que no se configurarlo para que me vaya en Alfresco 4.2c. me salta el siguiente error al subir algo via cmis "No se encontró el repositorio Cmis. Por favor, asegúrate de que la configuración de Cmis es correcta" ademas de fallar cuando le doy a sincronizar

no se exactamente que es Path Base Documentos, por eso lo he dejado por defecto: REDMINE (posiblemente me falle aqui)
Es posible que no sepa como sacar el ID del repositorio a sincronizar, lo que hago es fijarme en la url al acceder a el...

mi configuración es:
Url del servidor : http://192.168.3.193:8080/alfresco/service/cmis
Id del repositorio Cmis (el supuesto id del repositorio a sincronizar)
Path Base Documentos: REDMINE (???)
en Alfresco me he creado un nuevo espacio en la raiz del repositorio llamado REDMINE y es la id de este la que saco

¿Alguien sabe que estoy haciendo mal?

un saludo y gracias

**Comment by zuinqstudio** [comment]
Hola Takyo,

antes de nada decirte que la última versión de Alfresco con la que hemos probado el plugin es la 4.0, así que es posible que te encuentres con algunos problemas más. 

Dicho esto, puede que el problema esté en el Id de repositorio que has configurado; la forma más rápida de comprobar el id de tu repositorio es ejecutar desde un terminal.-

curl -uadmin:admin "http://192.168.3.193:8080/alfresco/service/cmis" | grep repositoryId

El id debería tener este formato xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

En cuanto al path base, no es más que la ruta a partir de la que quieres que cuelguen todas las carpetas/documentos que crees.

Saludos!

**Comment by Takyo** [comment]
Me funcionó como bien dijiste, Gracias!

Pd: confirmo que alfresco 4-2c comunity funciona sin problemas

un saludo

**Comment by zuinqstudio** [comment]
Perfecto, gracias por el feedback, tomamos nota :)
